import {
  Geist,
  Geist_Mono,
  Noto_Sans_JP,
  Noto_Sans_SC,
} from "next/font/google";
import localFont from "next/font/local";
import "./globals.scss";
import IntroAnimation from "./animations/IntroAnimation";
import ScrollTransitions from "./animations/ScrollTransitions";
import SmoothScroll from "./animations/SmoothScroll";
import ScrollDownArrow from "../components/ScrollDownArrow";
import MenuNav from "../components/MenuNav.client";
import PortfolioAnimations from "./animations/PortfolioAnimations";
import MobileMenuToggle from "../components/MobileMenuToggle.client";
import styles from "./layout.module.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorant = localFont({
  variable: "--font-cormorant",
  src: [
    {
      path: "../../public/Fonts/CormorantGaramond-VariableFont_wght.ttf",
      style: "normal",
      weight: "300 700",
    },
    {
      path: "../../public/Fonts/CormorantGaramond-Italic-VariableFont_wght.ttf",
      style: "italic",
      weight: "300 700",
    },
  ],
  display: "swap",
});

const notoJp = Noto_Sans_JP({
  variable: "--font-noto-jp",
  subsets: ["japanese"],
  weight: ["300", "400", "500", "600", "700"],
});

const notoSc = Noto_Sans_SC({
  variable: "--font-noto-sc",
  subsets: ["chinese-simplified"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  viewportFit: "cover",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cormorant.variable} ${notoJp.variable} ${notoSc.variable}`}
        data-header-state="hero"
      >
        <IntroAnimation />
        <SmoothScroll />
        <ScrollTransitions />
        <PortfolioAnimations />

        <div className={styles.shell}>
          {/* Fixed header/footer outlines (as in Figma) */}
          <div className={styles.headerBg} aria-hidden="true" />
          <div className={styles.footerBg} aria-hidden="true" />
          <div
            className={styles.headerLogo}
            data-anim="header-logo"
            aria-hidden="true"
          >
            <img className={styles.headerLogoImg} src="/svg/ctrl..svg" alt="" />
          </div>
          <div className={styles.topLineLeft} data-anim="line" aria-hidden="true" />
          <div className={styles.topLineRight} data-anim="line" aria-hidden="true" />
          <div
            className={styles.bottomLineLeft}
            data-anim="line"
            aria-hidden="true"
          />
          <div
            className={styles.bottomLineRight}
            data-anim="line"
            aria-hidden="true"
          />
          <MobileMenuToggle />

          <MenuNav />

          <ScrollDownArrow
            className={styles.scrollHint}
            iconClassName={styles.scrollHintIcon}
          />

          <div id="smooth-wrapper" className={styles.smoothWrapper}>
            <div id="smooth-content" className={styles.smoothContent}>
              <main className={styles.main}>{children}</main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
